apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: datatypehandler
  name: datatypehandler
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5003
  selector:
    io.kompose.service: datatypehandler

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: datatypehandler
spec:
  selector:
    matchLabels:
      io.kompose.service: datatypehandler
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/database: "true"
        io.kompose.service: datatypehandler
      name: datatypehandler
    spec:
      containers:
        - env:
            - name: DATABASE_NAME
              value: database
            - name: DATABASE_PORT
              value: "27017"
            - name: DATABASE_REPLICA_SET
              value: replica_set
            - name: DATABASE_URL
              value: mongodb://root:owl45#21@databaseprimary,databasesecondary
          image: learningorchestra/data_type_handler
          name: datatypehandler
          ports:
            - containerPort: 5003
          resources: {}
      restartPolicy: OnFailure
