apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: databasexecutor
  name: databasexecutor
spec:
  ports:
    - name: "5006"
      port: 5006
      targetPort: 5006
  selector:
    io.kompose.service: databasexecutor
status:
  loadBalancer: {}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: databasexecutor
spec:
  selector:
    matchLabels:
      io.kompose.service: databasexecutor
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/database: "true"
        io.kompose.service: databasexecutor
      name: databasexecutor
    spec:
      containers:
        - env:
            - name: DATABASE_NAME
              value: database
            - name: DATABASE_PORT
              value: "27017"
            - name: DATABASE_REPLICA_SET
              value: replica_set
            - name: DATABASE_URL
              value: mongodb://root:owl45#21@databaseprimary,databasesecondary
          image: learningorchestra/database_executor
          name: databasexecutor
          ports:
            - containerPort: 5006
          resources: {}
          volumeMounts:
            - mountPath: /explore
              name: database-executor
            - mountPath: /transform
              name: database-executor
            - mountPath: /models
              name: model
            - mountPath: /binaries
              name: binary-executor
            - mountPath: /code_executions
              name: code-executor
      restartPolicy: OnFailure
      volumes:
        - name: database-executor
          persistentVolumeClaim:
            claimName: database-executor
        - name: database-executor
          persistentVolumeClaim:
            claimName: database-executor
        - name: model
          persistentVolumeClaim:
            claimName: model
        - name: binary-executor
          persistentVolumeClaim:
            claimName: binary-executor
        - name: code-executor
          persistentVolumeClaim:
            claimName: code-executor
    status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-executor
  name: database-executor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
