apiVersion: v1
kind: Service
metadata:
  labels:
    app: database-arbiter-service
  name: database-arbiter-service
spec:
  ports:
    - name: "27019"
      port: 27019
      targetPort: 27017
  selector:
    app: database-arbiter-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-arbiter-deployment
  labels:
    app: database-arbiter-deployment
spec:
  selector:
    matchLabels:
      app: database-arbiter-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: database-arbiter-pod
      name: database-arbiter-pod
    spec:
      containers:
        - env:
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: database-arbiter-service
            - name: MONGODB_PRIMARY_HOST
              value: database-primary-service
            - name: MONGODB_PRIMARY_PORT_NUMBER
              value: "27017"
            - name: MONGODB_PRIMARY_ROOT_PASSWORD
              value: owl45#21
            - name: MONGODB_REPLICA_SET_KEY
              value: replicasetkey
            - name: MONGODB_REPLICA_SET_MODE
              value: arbiter
            - name: MONGODB_REPLICA_SET_NAME
              value: replica_set
          image: bitnami/mongodb:3.6.17-ol-7-r26
          name: database-arbiter-container
          ports:
            - containerPort: 27017
          resources: {}