apiVersion: v1
kind: Service
metadata:
  labels:
    app: projection-service
  name: projection-service
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "41000"
      port: 41000
      targetPort: 41000
  selector:
    app: projection-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: projection-deployment
  labels:
    app: projection-deployment
spec:
  selector:
    matchLabels:
      app: projection-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: projection-pod
      name: projection-pod
    spec:
      containers:
        - env:
            - name: DATABASE_NAME
              value: database
            - name: DATABASE_PORT
              value: "27017"
            - name: DATABASE_REPLICA_SET
              value: replica_set
            - name: DATABASE_URL
              value: mongodb://root:owl45#21@database-primary-service,database-secondary-service
          image: learningorchestra/projection:latest
          name: projection-container
          ports:
            - containerPort: 5001
            - containerPort: 41000
          resources: {}