apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sparkmaster
  name: sparkmaster
spec:
  ports:
    - name: "4040"
      port: 4040
      targetPort: 4040
    - name: "7077"
      port: 7077
      targetPort: 7077
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: sparkmaster

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkmaster
spec:
  selector:
    matchLabels:
      io.kompose.service: sparkmaster
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/database: "true"
        io.kompose.network/spark: "true"
        io.kompose.service: sparkmaster
      name: sparkmaster
    spec:
      containers:
        - env:
            - name: SPARK_ROLE
              value: master
          image: learningorchestra/spark
          name: sparkmaster
          ports:
            - containerPort: 4040
            - containerPort: 7077
            - containerPort: 8080
          resources: {}
      restartPolicy: OnFailure
