apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: sparkworker
  name: sparkworker
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "41352"
      port: 41352
      targetPort: 41352
  selector:
    io.kompose.service: sparkworker
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkworker
spec:
  selector:
    matchLabels:
      io.kompose.service: sparkworker
  replicas: 3
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/database: "true"
        io.kompose.network/spark: "true"
        io.kompose.service: sparkworker
      name: sparkworker
    spec:
      containers:
        - command:
            - dockerize
            - -wait
            - tcp://sparkmaster:7077
            - -timeout
            - 240s
            - /sbin/my_init
          env:
            - name: SPARK_MASTER
              value: sparkmaster
            - name: SPARK_ROLE
              value: slave
          image: learningorchestra/spark
          name: sparkworker
          ports:
            - containerPort: 8081
            - containerPort: 41352
          resources: {}
      restartPolicy: OnFailure
    status: {}
